data:
  address: localhost
  database: minecraft
  username: root
  password: ''
  pool-settings:
    maximum-pool-size: 10
    minimum-idle: 10
    maximum-lifetime: 1800000 # 30 minutes
    keepalive-time: 0
    connection-timeout: 5000 # 5 seconds
  properties:
    useSSL: true
    verifyServerCertificate: true
  table-prefix: 'xenon_'