name: Xenon
version: ${version}
main: dev.portero.xenon.Xenon
author: Portero
description: A modern Minecraft plugin crafted for the latest version, blending learning with pure fun.
api-version: 1.20
